doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '16'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Auth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Domain/Entity'
                prefix: 'App\Auth\Domain\Entity'
                alias: Auth
            Profiles:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Profiles/Domain/Entity'
                prefix: 'App\Profiles\Domain\Entity'
                alias: Profiles
            Routes:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Routes/Domain/Entity'
                prefix: 'App\Routes\Domain\Entity'
                alias: Routes
            Notifications:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Notifications/Domain/Entity'
                prefix: 'App\Notifications\Domain\Entity'
                alias: Notifications
            Suscriptions:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Suscriptions/Domain/Entity'
                prefix: 'App\Suscriptions\Domain\Entity'
                alias: Suscriptions
        controller_resolver:
            auto_mapping: false
        # metadata_cache_driver:
        #     type: pool 
        #     pool: cache.adapter.filesystem
        # query_cache_driver:
        #     type: pool
        #     pool: cache.adapter.filesystem
        # result_cache_driver:
        #     type: pool
        #     pool: cache.adapter.filesystem
        # second_level_cache:
        #     enabled: true
        #     region_cache_driver:
        #         type: pool
        #         pool: cache.adapter.filesystem

# framework:
#     cache:
#         pools:
#             doctrine.result_cache_pool:
#                 adapter: cache.adapter.redis
#                 provider: redis://localhost

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
