nelmio_cors:
    defaults:
        origin_regex: true # usa regex para origin
        allow_credentials: true # permite cookies y cabezeras de autenticación (Authorization)
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type','Authorization','X-Requested-With','Accept']
        expose_headers: ['Link','Set-Cookie']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/': null
