# controllers:
#     resource:
#         path: ../src/Presentation/Controller/
#         namespace: App\Presentation\Controller
#     type: attribute

api_refresh_token:
    path: /api/token/refresh

api_token_invalidate:
    path: /api/token/invalidate
