# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
    
    App\Auth\:
        resource: '../src/Auth'
        exclude:
            - '../src/Auth/Domain/Entity/'

    App\Profiles\:
        resource: '../src/Profiles'
        exclude:
            - '../src/Profiles/Domain/Entity/'

    App\Routes\:
        resource: '../src/Routes'
        exclude:
            - '../src/Routes/Domain/Entity/'

    App\Shared\Domain\Exception\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Notifications\:
        resource: '../src/Notifications'
        exclude:
            - '../src/Notifications/Domain/Entity/'

    App\Suscriptions\:
        resource: '../src/Suscriptions'
        exclude:
            - '../src/Suscriptions/Domain/Entity/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
